help:
  @just --list

build:
  pio run -e ${PIO_ENV:-Actionneurs}

motor-build:
  pio run -e Motor

test:
  pio test -e ${PIO_ENV:-Actionneurs}

upload:
  pio run -e ${PIO_ENV:-Actionneurs} -t upload 
