; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:Motor]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = 
	+<main_robot.*>
build_type = debug
lib_ldf_mode = chain+
board_build.partitions = huge_app.csv
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
lib_deps = 
	bblanchon/ArduinoJson @ ^6.21.0
	gin66/FastAccelStepper@^1.2.5

[env:Actionneurs]
platform = espressif32
board = esp32dev
framework = arduino
monitor_filters = 
	esp32_exception_decoder
	send_on_enter
build_type = debug
monitor_speed = 115200
build_src_filter =
	+<main_actionneurs.*>
lib_deps =
  https://github.com/xreef/PCF8575_library.git
	https://github.com/RobTillaart/PCF8575.git
  madhephaestus/ESP32Servo @ ^3.0.6
	gin66/FastAccelStepper@^1.2.5

[env:full]
platform = espressif32
board = esp32dev
framework = arduino
monitor_filters = 
	esp32_exception_decoder
	send_on_enter
build_type = debug
monitor_speed = 115200
build_src_filter =
	+<bsp.*>
lib_deps =
  https://github.com/vChavezB/qpcpp_esp32
  https://github.com/xreef/PCF8575_library.git
	https://github.com/RobTillaart/PCF8575.git
  madhephaestus/ESP32Servo @ ^3.0.6
	gin66/FastAccelStepper@^1.2.5
build_flags =
    -I lib/qpcpp/include
    -I lib/qpcpp/ports/freertos
