[Unit]
Description=Network Manager (Auto-enabled on STKbtw Live)
After=network-pre.target
Wants=network.target

[Service]
# Redémarrage automatique en cas de plantage sur le PC embarqué
Restart=always
RestartSec=2s
